<?php


namespace frontend\assets;

use yii\web\AssetBundle;

class CartAsset extends AppAsset
{
    public $js = [
        'js/cart.js'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}