<?php


namespace frontend\widgets;

use frontend\assets\CartAsset;
use yii\bootstrap\Widget;


class Cart extends Widget
{
    public $action_add;
    public $action_delete;
    public $action_all;
    public $button_add;
    public $data_attr;
    public $csrf_token;
    protected $conf;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $options = [
            'action_add' => $this->action_add,
            'action_delete' => $this->action_delete,
            'action_all' => $this->action_all,
            'data_attr' => $this->data_attr,
            'csrf_token' => $this->csrf_token,
        ];
        $this->conf = json_encode($options);
    }

    public function run()
    {
        echo $this->registerScript();
    }

    public function registerScript()
    {
        $view = $this->getView();
        CartAsset::register($view);

        $js = <<< JS
             const cart = new Cart($this->conf);
             $('$this->button_add').click((e) => {
                 cart.add($(e.target).attr('$this->data_attr'), 1);
             });
JS;
        $view->registerJs($js);
    }
}